-- join A(id), B(A_id)


CREATE TABLE CUSTOMER (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCAHR(100),
);

CREATE TABLE ORDER(
    ORDER_ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCAHR(100),
    CUTOMER_ID INT ,
    FOREIGN KEY(CUTOMER_ID) REFERENCES CUTOMER(ID)
);

-- INNER JOIN - DATA WILL BE ONLY REALTED

SELECT * FROM CUSTOMER 
INNER JOIN ORDER ON CUSTOMER.ID = ORDER.CUSTOMER_ID ;


-- LEFT JOIN - ALL DATA FROM 
SELECT * FROM CUSTOMER 
LEFT JOIN ORDER ON CUSTOMER.ID = ORDER.CUSTOMER_ID;

-- RIGHT JOIN - ALL FROM RIGHT TABLE
SELECT * FROM CUSTOMER 
RIGHT JOIN ORDER ON CUTOMER.ID = ORDER.CUSTOMER_ID;

-- ON DELETE DATA

CREATE TABLE ORDER(
    ORDER_ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCAHR(100),
    CUTOMER_ID INT ,
    FOREIGN KEY(CUTOMER_ID) REFERENCES CUTOMER(ID) ON DELETE CASCADE
);